/**
 * Wire types for the downloadable language packs.
 *
 * English ships bundled in the app. Every other language lives only on GitHub
 * `main` as src/locales/<code>/translation.json and is fetched on demand. The
 * manifest (src/locales/manifest.json, generated by scripts/gen-locale-manifest.mjs)
 * is the index the language picker reads: it lists each language and how complete
 * its catalog is relative to the English source.
 */

/** One language's entry in the manifest. */
export interface LocaleManifestEntry {
  /** BCP 47 code, e.g. 'de' or 'pt-BR'. */
  code: string;
  /** Native display name, e.g. 'Deutsch'. */
  name: string;
  /** Keys present (and non-empty) in this language's catalog. */
  translatedKeys: number;
  /** Percentage of the English source translated, 0-100 (rounded). */
  pct: number;
}

/** The locale index served from GitHub `main` (with a bundled fallback copy). */
export interface LocaleManifest {
  /** Source language every percentage is measured against. Always 'en'. */
  sourceLanguage: string;
  /** Total translatable keys in the English source. */
  totalKeys: number;
  /** Every language with a catalog on `main`, English included. */
  languages: LocaleManifestEntry[];
}

/** A language catalog fetched (or read from cache) by the main process. */
export interface DownloadedLocale {
  code: string;
  /** The flat/nested i18next translation catalog. */
  catalog: Record<string, unknown>;
}
